/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Fundamental.Orçamento;

import controle.ControleOrcamento;
import java.awt.Font;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.Orcamento;
import modelo.OrcamentoProduto;

/**
 *
 * @author Maycon
 */
public class OrcamentoDevolverProduto extends javax.swing.JDialog {

    /**
     * Creates new form OrcamentoDevolverProduto
     */
//    private Orcamento orcamentoDevolver = new Orcamento();

    /*
    definindo o defaultModel da tabela de produtos a devolver
     */
    private DefaultTableModel tabProdutoADevolver;

    /*
    definindo o defaultModel da tabela de produtos devolvidos
     */
    private DefaultTableModel tabProdutoDevolvido;

    /*
    lista de orcamento para os produtos a devolver
     */
    private ArrayList<OrcamentoProduto> listOrcamentoProduto = new ArrayList<>();

    /*
    lista de orcamento para os produtos devolvidos
     */
    private ArrayList<OrcamentoProduto> listOrcamentoProdutoDevolvido = new ArrayList<>();

    private SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/yyyy");

    private Date hoje;

    private Orcamento orcamentoDevolvido;

    OrcamentoProduto orcProdutoDevolver = new OrcamentoProduto();

    DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
    DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
    public OrcamentoDevolverProduto(java.awt.Frame parent, boolean modal, Orcamento orcamento) {
        super(parent, modal);
        initComponents();
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        tabProdutoOrcamento.setFont(new Font("SansSerif", 0, 14));
        tabProdutosDevolvidos.setFont(new Font("SansSerif", 0, 14));

        direita.setBackground(new java.awt.Color(209, 209, 209));
        direita.setForeground(new java.awt.Color(102, 102, 102));
        esquerda.setBackground(new java.awt.Color(209, 209, 209));
        esquerda.setForeground(new java.awt.Color(102, 102, 102));
        tabProdutoOrcamento.getColumnModel().getColumn(1).setCellRenderer(direita);
        tabProdutoOrcamento.getColumnModel().getColumn(2).setCellRenderer(direita);
        tabProdutoOrcamento.getColumnModel().getColumn(0).setCellRenderer(esquerda);
        
        tabProdutosDevolvidos.getColumnModel().getColumn(0).setCellRenderer(esquerda);
        tabProdutosDevolvidos.getColumnModel().getColumn(1).setCellRenderer(direita);
        tabProdutosDevolvidos.getColumnModel().getColumn(2).setCellRenderer(direita);
        
        
        

        botDevolverProduto.setVerticalTextPosition(SwingConstants.BOTTOM);
        botDevolverProduto.setHorizontalTextPosition(SwingConstants.LEFT);

        tabProdutoADevolver = (DefaultTableModel) tabProdutoOrcamento.getModel();

        tabProdutoDevolvido = (DefaultTableModel) tabProdutosDevolvidos.getModel();

        listOrcamentoProduto.addAll(orcamento.getListaOrcamento());
        atualizarTabelaProdutoOrcamento(listOrcamentoProduto);

        hoje = new Date();
        orcamentoDevolvido = orcamento;



        labDataDevolvido.setText(formatar.format(hoje));
        labDataEntregue.setText(formatar.format(orcamento.getDataEntrega()));
        labNomeCliente.setText(orcamento.getClienteCod().getClienteNome());
        labValorOrcamento.setText(doubleString(orcamento.getValorOrc()));
        darTamanhoAColunaOrcamento();
        darTamanhoAColunaOrcamentoDevolvido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        botFecharNormal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labNomeCliente = new javax.swing.JLabel();
        labValorOrcamento = new javax.swing.JLabel();
        labDataEntregue = new javax.swing.JLabel();
        labDataDevolvido = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rSPanelGradiente2 = new rspanelgradiente.RSPanelGradiente();
        botDevolver = new javax.swing.JButton();
        botVoltar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProdutoOrcamento = new rojerusan.RSTableMetro();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        botDevolverProduto = new javax.swing.JButton();
        labNomeProduto = new javax.swing.JLabel();
        jSpinerQuantidadeDevolvida = new com.toedter.components.JSpinField();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabProdutosDevolvidos = new rojerusan.RSTableMetro();
        botVoltarProduto = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        labValorAPagar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        rSPanelGradiente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botFecharNormal.setBackground(new java.awt.Color(255, 0, 0));
        botFecharNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/fechar34px.png"))); // NOI18N
        botFecharNormal.setContentAreaFilled(false);
        botFecharNormal.setFocusable(false);
        botFecharNormal.setOpaque(true);
        botFecharNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botFecharNormalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DEVOLVER ORÇAMENTO");

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botFecharNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botFecharNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 0, 0))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Orçamento", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("NOME CLIENTE:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("VALOR:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("DATA ENTREGUE:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("DATA DEVOLVIDO:");

        labNomeCliente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labNomeCliente.setForeground(new java.awt.Color(0, 0, 255));

        labValorOrcamento.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        labValorOrcamento.setForeground(new java.awt.Color(255, 0, 0));

        labDataEntregue.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labDataEntregue.setForeground(new java.awt.Color(0, 0, 255));

        labDataDevolvido.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labDataDevolvido.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labValorOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labDataEntregue, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labDataDevolvido, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labDataEntregue, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labDataDevolvido, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labValorOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botDevolver.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        botDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/confirmar18px.png"))); // NOI18N
        botDevolver.setText("CONFIRMAR");
        botDevolver.setFocusable(false);
        botDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDevolverActionPerformed(evt);
            }
        });

        botVoltar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        botVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/voltar18px.png"))); // NOI18N
        botVoltar.setText("VOLTAR");
        botVoltar.setFocusable(false);
        botVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelGradiente2Layout = new javax.swing.GroupLayout(rSPanelGradiente2);
        rSPanelGradiente2.setLayout(rSPanelGradiente2Layout);
        rSPanelGradiente2Layout.setHorizontalGroup(
            rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente2Layout.createSequentialGroup()
                .addComponent(botVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        rSPanelGradiente2Layout.setVerticalGroup(
            rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botDevolver)
                    .addComponent(botVoltar))
                .addGap(1, 1, 1))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PRODUTOS NO ORÇAMENTO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabProdutoOrcamento.setAutoCreateRowSorter(true);
        tabProdutoOrcamento.setBackground(new java.awt.Color(250, 250, 250));
        tabProdutoOrcamento.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabProdutoOrcamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Valor", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabProdutoOrcamento.setAltoHead(40);
        tabProdutoOrcamento.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tabProdutoOrcamento.setAutoscrolls(false);
        tabProdutoOrcamento.setColorBackgoundHead(new java.awt.Color(250, 250, 250));
        tabProdutoOrcamento.setColorFilasBackgound1(new java.awt.Color(209, 209, 209));
        tabProdutoOrcamento.setColorFilasBackgound2(new java.awt.Color(209, 209, 209));
        tabProdutoOrcamento.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        tabProdutoOrcamento.setColorFilasForeground2(new java.awt.Color(102, 102, 102));
        tabProdutoOrcamento.setColorForegroundHead(new java.awt.Color(51, 51, 51));
        tabProdutoOrcamento.setColorSelBackgound(new java.awt.Color(40, 53, 147));
        tabProdutoOrcamento.setFuenteFilas(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tabProdutoOrcamento.setFuenteFilasSelect(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tabProdutoOrcamento.setFuenteHead(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tabProdutoOrcamento.setGridColor(new java.awt.Color(204, 204, 204));
        tabProdutoOrcamento.setGrosorBordeFilas(0);
        tabProdutoOrcamento.setGrosorBordeHead(0);
        tabProdutoOrcamento.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabProdutoOrcamento.setMultipleSeleccion(false);
        tabProdutoOrcamento.setOpaque(false);
        tabProdutoOrcamento.setRowHeight(30);
        tabProdutoOrcamento.setSelectionBackground(new java.awt.Color(40, 53, 147));
        tabProdutoOrcamento.getTableHeader().setReorderingAllowed(false);
        tabProdutoOrcamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabProdutoOrcamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabProdutoOrcamento);
        if (tabProdutoOrcamento.getColumnModel().getColumnCount() > 0) {
            tabProdutoOrcamento.getColumnModel().getColumn(0).setResizable(false);
            tabProdutoOrcamento.getColumnModel().getColumn(1).setResizable(false);
            tabProdutoOrcamento.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("PRODUTO:");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("QUANTIDADE DEVOLVIDA:");

        botDevolverProduto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        botDevolverProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/devolver18px.png"))); // NOI18N
        botDevolverProduto.setText("DEVOLVER");
        botDevolverProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botDevolverProduto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        botDevolverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDevolverProdutoActionPerformed(evt);
            }
        });

        labNomeProduto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labNomeProduto.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinerQuantidadeDevolvida, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botDevolverProduto)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(jSpinerQuantidadeDevolvida, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botDevolverProduto))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PRODUTOS DEVOLVIDOS");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabProdutosDevolvidos.setAutoCreateRowSorter(true);
        tabProdutosDevolvidos.setBackground(new java.awt.Color(250, 250, 250));
        tabProdutosDevolvidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabProdutosDevolvidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Valor", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabProdutosDevolvidos.setAltoHead(40);
        tabProdutosDevolvidos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tabProdutosDevolvidos.setAutoscrolls(false);
        tabProdutosDevolvidos.setColorBackgoundHead(new java.awt.Color(250, 250, 250));
        tabProdutosDevolvidos.setColorFilasBackgound1(new java.awt.Color(209, 209, 209));
        tabProdutosDevolvidos.setColorFilasBackgound2(new java.awt.Color(209, 209, 209));
        tabProdutosDevolvidos.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        tabProdutosDevolvidos.setColorFilasForeground2(new java.awt.Color(102, 102, 102));
        tabProdutosDevolvidos.setColorForegroundHead(new java.awt.Color(51, 51, 51));
        tabProdutosDevolvidos.setColorSelBackgound(new java.awt.Color(40, 53, 147));
        tabProdutosDevolvidos.setFuenteFilas(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tabProdutosDevolvidos.setFuenteFilasSelect(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tabProdutosDevolvidos.setFuenteHead(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tabProdutosDevolvidos.setGridColor(new java.awt.Color(204, 204, 204));
        tabProdutosDevolvidos.setGrosorBordeFilas(0);
        tabProdutosDevolvidos.setGrosorBordeHead(0);
        tabProdutosDevolvidos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabProdutosDevolvidos.setMultipleSeleccion(false);
        tabProdutosDevolvidos.setOpaque(false);
        tabProdutosDevolvidos.setRowHeight(30);
        tabProdutosDevolvidos.setSelectionBackground(new java.awt.Color(40, 53, 147));
        tabProdutosDevolvidos.getTableHeader().setReorderingAllowed(false);
        tabProdutosDevolvidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabProdutosDevolvidosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabProdutosDevolvidos);
        if (tabProdutosDevolvidos.getColumnModel().getColumnCount() > 0) {
            tabProdutosDevolvidos.getColumnModel().getColumn(0).setResizable(false);
            tabProdutosDevolvidos.getColumnModel().getColumn(1).setResizable(false);
            tabProdutosDevolvidos.getColumnModel().getColumn(2).setResizable(false);
        }

        botVoltarProduto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        botVoltarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/voltarDevolção18px.png"))); // NOI18N
        botVoltarProduto.setText("VOLTAR PRODUTO");
        botVoltarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVoltarProdutoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("TOTAL À PAGAR:");

        labValorAPagar.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botVoltarProduto)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labValorAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labValorAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botVoltarProduto)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelGradiente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(rSPanelGradiente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botFecharNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botFecharNormalActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_botFecharNormalActionPerformed

    private void botDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDevolverActionPerformed

        orcamentoDevolvido.setDataDevolucao(hoje);

        orcamentoDevolvido.setListaOrcamento(listOrcamentoProdutoDevolvido);
        
        ControleOrcamento contOrcamento = new ControleOrcamento();
        
        contOrcamento.finalizarConsignacao(orcamentoDevolvido);
        
        dispose();

    }//GEN-LAST:event_botDevolverActionPerformed

    private void botVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVoltarActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_botVoltarActionPerformed

    private void tabProdutoOrcamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabProdutoOrcamentoMouseClicked

        int linhaProdutoOrcamento = -1;
        linhaProdutoOrcamento = tabProdutoOrcamento.getSelectedRow();

        if (linhaProdutoOrcamento != -1) {
            OrcamentoProduto orcamentoDolvido = new OrcamentoProduto();
            orcamentoDolvido = listOrcamentoProduto.get(linhaProdutoOrcamento);
            // labValorAPagar.setText(doubleString(orcamentoDolvido.getValor()));
            labNomeProduto.setText(orcamentoDolvido.getProdutoCod().getProdutoNome());
        } else {
            JOptionPane.showMessageDialog(null, "SELECIONE ALGUÉM NA TABELA");
        }
    }//GEN-LAST:event_tabProdutoOrcamentoMouseClicked

    private void tabProdutosDevolvidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabProdutosDevolvidosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabProdutosDevolvidosMouseClicked

    private void botDevolverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDevolverProdutoActionPerformed

        int linhaTabProdutoOrcamento = -1;

        linhaTabProdutoOrcamento = tabProdutoOrcamento.getSelectedRow();

        if (!(listOrcamentoProduto.isEmpty())) {
            if (linhaTabProdutoOrcamento != -1) {

                if (jSpinerQuantidadeDevolvida.getValue() > -1) {
                    orcProdutoDevolver = listOrcamentoProduto.get(linhaTabProdutoOrcamento);

                    orcProdutoDevolver.setQuantidadeDevolvida(jSpinerQuantidadeDevolvida.getValue());

                    listOrcamentoProdutoDevolvido.add(orcProdutoDevolver);

                    atualizarTabelaProdutoOrcamentoDevolvido(listOrcamentoProdutoDevolvido);

                    listOrcamentoProduto.remove(linhaTabProdutoOrcamento);

                    atualizarTabelaProdutoOrcamento(listOrcamentoProduto);

                    labValorAPagar.setText(calcularValorDeProdutosDevolvidos(listOrcamentoProdutoDevolvido));
                    jSpinerQuantidadeDevolvida.setValue(0);
                } else {
                    JOptionPane.showMessageDialog(null, "QUANTIDADE DEVOLVIDA INVÁLIDO!");
                }

            } else {
                JOptionPane.showMessageDialog(null, "SELECIONE UM PRODUTO PARA SER DEVOLVIDO!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "NÃO TEM PRODUTOS PARA SER DEVOLVIDOS!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_botDevolverProdutoActionPerformed

    private void botVoltarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVoltarProdutoActionPerformed

        if (!(listOrcamentoProdutoDevolvido.isEmpty())) {

            int linhaVoltarDevolucao = -1;
            linhaVoltarDevolucao = tabProdutosDevolvidos.getSelectedRow();

            if (linhaVoltarDevolucao != -1) {
                OrcamentoProduto orcProdDevol = new OrcamentoProduto();
                orcProdDevol = listOrcamentoProdutoDevolvido.get(linhaVoltarDevolucao);
                orcProdDevol.setQuantidadeDevolvida(0);
                listOrcamentoProduto.add(orcProdDevol);
                listOrcamentoProdutoDevolvido.remove(linhaVoltarDevolucao);
                atualizarTabelaProdutoOrcamento(listOrcamentoProduto);
                atualizarTabelaProdutoOrcamentoDevolvido(listOrcamentoProdutoDevolvido);
                labValorAPagar.setText(calcularValorDeProdutosDevolvidos(listOrcamentoProdutoDevolvido));
                orcamentoDevolvido.setListaOrcamento(listOrcamentoProdutoDevolvido);
            } else {
                JOptionPane.showMessageDialog(null, "SELECIONE UM PRODUTO PARA SER CORRIGIDO SUA DEVOLUÇÃO!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "NÃO TEM PRODUTOS DEVOLVIDOS!");
        }

    }//GEN-LAST:event_botVoltarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrcamentoDevolverProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrcamentoDevolverProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrcamentoDevolverProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrcamentoDevolverProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OrcamentoDevolverProduto dialog = new OrcamentoDevolverProduto(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botDevolver;
    private javax.swing.JButton botDevolverProduto;
    private javax.swing.JButton botFecharNormal;
    private javax.swing.JButton botVoltar;
    private javax.swing.JButton botVoltarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.components.JSpinField jSpinerQuantidadeDevolvida;
    private javax.swing.JLabel labDataDevolvido;
    private javax.swing.JLabel labDataEntregue;
    private javax.swing.JLabel labNomeCliente;
    private javax.swing.JLabel labNomeProduto;
    private javax.swing.JLabel labValorAPagar;
    private javax.swing.JLabel labValorOrcamento;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente2;
    private rojerusan.RSTableMetro tabProdutoOrcamento;
    private rojerusan.RSTableMetro tabProdutosDevolvidos;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabelaProdutoOrcamento(ArrayList<OrcamentoProduto> listaProdutoOrcamento) {

        while (tabProdutoADevolver.getRowCount() > 0) {
            // apaga a primeira linha
            tabProdutoADevolver.removeRow(0);
        }
        for (OrcamentoProduto o : listaProdutoOrcamento) {
            // adiciona uma linha na tabela
            // o object criado tem que ter a mesma quantidade
            // de elementos que foi definida na tabela, 
            // como também os mesmos tipos
            tabProdutoADevolver.addRow(new Object[]{o.getProdutoCod().getProdutoNome(), doubleString(o.getValor()), o.getQuantidade()});
        }
    }

    public String doubleString(double d) {

        Locale.setDefault(new Locale("pt", "BR"));
        DecimalFormat df = new DecimalFormat("#,##0.00", new DecimalFormatSymbols(new Locale("pt", "BR")));
        String s = df.format(d);
        return s;
    }

    private void atualizarTabelaProdutoOrcamentoDevolvido(ArrayList<OrcamentoProduto> listaProdutoOrcamentoDevolvidos) {

        while (tabProdutoDevolvido.getRowCount() > 0) {
            // apaga a primeira linha
            tabProdutoDevolvido.removeRow(0);
        }
        for (OrcamentoProduto o : listaProdutoOrcamentoDevolvidos) {
            // adiciona uma linha na tabela
            // o object criado tem que ter a mesma quantidade
            // de elementos que foi definida na tabela, 
            // como também os mesmos tipos
            tabProdutoDevolvido.addRow(new Object[]{o.getProdutoCod().getProdutoNome(), doubleString(o.getValor()), o.getQuantidadeDevolvida()});
        }
    }

    private String calcularValorDeProdutosDevolvidos(ArrayList<OrcamentoProduto> listaProdDevolvido) {
        double valor = 0;

        for (OrcamentoProduto op : listaProdDevolvido) {
            valor += op.getValor() * (op.getQuantidade() - op.getQuantidadeDevolvida());
        }
        return doubleString(valor);
    }

    
    public void darTamanhoAColunaOrcamento() {
        tabProdutoOrcamento.getColumnModel().getColumn(0).setPreferredWidth(300);
        tabProdutoOrcamento.getColumnModel().getColumn(1).setPreferredWidth(35);
        tabProdutoOrcamento.getColumnModel().getColumn(2).setPreferredWidth(35);        
    }
    
    public void darTamanhoAColunaOrcamentoDevolvido() {
        tabProdutosDevolvidos.getColumnModel().getColumn(0).setPreferredWidth(300);
        tabProdutosDevolvidos.getColumnModel().getColumn(1).setPreferredWidth(35);
        tabProdutosDevolvidos.getColumnModel().getColumn(2).setPreferredWidth(35);        
    }
}
