/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Fornecedor;

import controle.ControleFornecedor;
import controle.IntegridadeException;
import controle.NaoExisteException;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import modelo.Fornecedor;
import static org.jdesktop.observablecollections.ObservableCollections.observableList;

/**
 *
 * @author Maycon
 */
public class viewFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form viewFornecedor
     */
    Fornecedor fornecedor;
    ControleFornecedor contFornecedor;

    public viewFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        contFornecedor = new ControleFornecedor();
        listFornecedor.addAll(contFornecedor.listarTodos());
        txtBuscar.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listFornecedor = observableList(new ArrayList<>());
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botFechar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        rSPanelGradiente2 = new rspanelgradiente.RSPanelGradiente();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        labRazaoSocial = new javax.swing.JLabel();
        labNomeFantasia = new javax.swing.JLabel();
        labCidade = new javax.swing.JLabel();
        labCNPJ = new javax.swing.JLabel();
        labNomeContato = new javax.swing.JLabel();
        labTelefone = new javax.swing.JLabel();
        labEmail = new javax.swing.JLabel();
        botAlterar = new javax.swing.JButton();
        botExcluir = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        txtBuscar = new javax.swing.JTextField();
        botLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabFornecedor = new rojerusan.RSTableMetro();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        botVoltar = new javax.swing.JButton();
        botNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(26, 35, 126));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fornecedor");

        botFechar.setBackground(new java.awt.Color(26, 35, 126));
        botFechar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botFechar.setForeground(new java.awt.Color(255, 255, 255));
        botFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/close.png"))); // NOI18N
        botFechar.setContentAreaFilled(false);
        botFechar.setOpaque(true);
        botFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2))
            .addComponent(botFechar)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        rSPanelGradiente2.setColorPrimario(new java.awt.Color(26, 35, 126));
        rSPanelGradiente2.setColorSecundario(new java.awt.Color(103, 58, 183));
        rSPanelGradiente2.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.VERTICAL);
        rSPanelGradiente2.setPreferredSize(new java.awt.Dimension(336, 135));

        rSPanelImage1.setBackground(new java.awt.Color(153, 153, 153));
        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imagem/asfalt-light.png"))); // NOI18N
        rSPanelImage1.setPreferredSize(new java.awt.Dimension(336, 135));

        labRazaoSocial.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labRazaoSocial.setForeground(new java.awt.Color(255, 255, 255));
        labRazaoSocial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/empresa28px.png"))); // NOI18N

        labNomeFantasia.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labNomeFantasia.setForeground(new java.awt.Color(255, 255, 255));
        labNomeFantasia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/nomeFantasia24px.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labRazaoSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labNomeFantasia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labRazaoSocial)
                .addGap(18, 18, 18)
                .addComponent(labNomeFantasia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rSPanelGradiente2Layout = new javax.swing.GroupLayout(rSPanelGradiente2);
        rSPanelGradiente2.setLayout(rSPanelGradiente2Layout);
        rSPanelGradiente2Layout.setHorizontalGroup(
            rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        rSPanelGradiente2Layout.setVerticalGroup(
            rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente2Layout.createSequentialGroup()
                .addComponent(rSPanelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        labCidade.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/position.png"))); // NOI18N

        labCNPJ.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labCNPJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/card.png"))); // NOI18N

        labNomeContato.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labNomeContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/nomeContato16px.png"))); // NOI18N

        labTelefone.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/phone.png"))); // NOI18N

        labEmail.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/mail.png"))); // NOI18N

        botAlterar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/edit18px.png"))); // NOI18N
        botAlterar.setText("ALTERAR");
        botAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAlterarActionPerformed(evt);
            }
        });

        botExcluir.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/delete18px.png"))); // NOI18N
        botExcluir.setText("EXCLUIR");
        botExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelGradiente2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labCNPJ)
                    .addComponent(labCidade))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(labEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labNomeContato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(botAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botExcluir))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(rSPanelGradiente2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(labCNPJ)
                .addGap(30, 30, 30)
                .addComponent(labCidade)
                .addGap(30, 30, 30)
                .addComponent(labNomeContato)
                .addGap(30, 30, 30)
                .addComponent(labTelefone)
                .addGap(30, 30, 30)
                .addComponent(labEmail)
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botExcluir)
                    .addComponent(botAlterar))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel1.setDoubleBuffered(false);
        kGradientPanel1.setkEndColor(new java.awt.Color(26, 35, 126));
        kGradientPanel1.setkStartColor(new java.awt.Color(40, 53, 147));

        txtBuscar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar.setOpaque(false);
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        botLimpar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/limpar18px.png"))); // NOI18N
        botLimpar.setText("LIMPAR");
        botLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimparActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOME CONTATO:");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botLimpar)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botLimpar)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10))
        );

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabFornecedor.setAutoCreateRowSorter(true);
        tabFornecedor.setBackground(new java.awt.Color(250, 250, 250));
        tabFornecedor.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tabFornecedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tabFornecedor.setAutoscrolls(false);
        tabFornecedor.setColorBackgoundHead(new java.awt.Color(250, 250, 250));
        tabFornecedor.setColorFilasBackgound1(new java.awt.Color(209, 209, 209));
        tabFornecedor.setColorFilasBackgound2(new java.awt.Color(250, 250, 250));
        tabFornecedor.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        tabFornecedor.setColorFilasForeground2(new java.awt.Color(102, 102, 102));
        tabFornecedor.setColorForegroundHead(new java.awt.Color(51, 51, 51));
        tabFornecedor.setColorSelBackgound(new java.awt.Color(40, 53, 147));
        tabFornecedor.setFuenteFilas(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tabFornecedor.setFuenteFilasSelect(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tabFornecedor.setFuenteHead(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tabFornecedor.setGridColor(new java.awt.Color(204, 204, 204));
        tabFornecedor.setGrosorBordeFilas(0);
        tabFornecedor.setGrosorBordeHead(0);
        tabFornecedor.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabFornecedor.setMultipleSeleccion(false);
        tabFornecedor.setOpaque(false);
        tabFornecedor.setRowHeight(30);
        tabFornecedor.setSelectionBackground(new java.awt.Color(63, 81, 181));
        tabFornecedor.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listFornecedor, tabFornecedor);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fornecedorNomeFantasia}"));
        columnBinding.setColumnName("Nome Fantasia");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${forncedorNomeContato}"));
        columnBinding.setColumnName("Contato");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fornecedorTelefoneCelular}"));
        columnBinding.setColumnName("Telefone");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tabFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabFornecedor);
        if (tabFornecedor.getColumnModel().getColumnCount() > 0) {
            tabFornecedor.getColumnModel().getColumn(0).setResizable(false);
            tabFornecedor.getColumnModel().getColumn(1).setResizable(false);
            tabFornecedor.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        kGradientPanel3.setkEndColor(new java.awt.Color(40, 53, 147));
        kGradientPanel3.setkStartColor(new java.awt.Color(26, 35, 126));

        botVoltar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/voltar18px.png"))); // NOI18N
        botVoltar.setText("VOLTAR");
        botVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVoltarActionPerformed(evt);
            }
        });

        botNovo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/add18px.png"))); // NOI18N
        botNovo.setText("INSERIR NOVO FORNECEDOR");
        botNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(botVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botNovo)
                .addGap(5, 5, 5))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botVoltar)
                    .addComponent(botNovo))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1052, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botFecharActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_botFecharActionPerformed

    private void botAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAlterarActionPerformed

        int linha = -1;
        linha = tabFornecedor.getSelectedRow();
        if (linha != -1) {
            boolean consulta = true;
            fornecedor = listFornecedor.get(linha);
            viewDadosFornecedor alterar = new viewDadosFornecedor(null, true, fornecedor, consulta);
            alterar.setVisible(true);
            listFornecedor.clear();
            listFornecedor.addAll(contFornecedor.listarTodos());
            limparLab();
            fornecedor = null;
        } else {
            JOptionPane.showMessageDialog(null, "SELECIONE ALGUÉM NA TABELA PARA ALTERAR");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_botAlterarActionPerformed

    private void botExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botExcluirActionPerformed

        int linhaExcluir = -1;
        linhaExcluir = tabFornecedor.getSelectedRow();
        if (linhaExcluir != -1) {
            fornecedor = listFornecedor.get(linhaExcluir);
            int op = JOptionPane.showConfirmDialog(this,
                    "Confirma a exclusão do fornecedor "
                    + fornecedor.getForncedorNomeContato() + "da empresa " + fornecedor.getFornecedorNomeFantasia() + "?",
                    "Exclusão de fornecedor",
                    JOptionPane.YES_NO_OPTION);

            if (op == JOptionPane.YES_OPTION) {
                // chama o controle para excluir o usuário
                try {
                    contFornecedor.excluir(fornecedor.getForncedorID());
                    /// JOptionPane.showMessageDialog(this, "O usuário foi excluído.");
                    listFornecedor.clear();
                    listFornecedor.addAll(contFornecedor.listarTodos());
                    limparLab();
                } catch (NaoExisteException | IntegridadeException e) {

                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Funcionário Na Tabela Para Ser Excluido");
        }
    }//GEN-LAST:event_botExcluirActionPerformed

    private void botLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimparActionPerformed

        txtBuscar.setText("");
        limparLab();
        listFornecedor.clear();
        listFornecedor.addAll(contFornecedor.listarTodos());

        // TODO add your handling code here:
    }//GEN-LAST:event_botLimparActionPerformed

    private void tabFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabFornecedorMouseClicked
        int linha = -1;
        linha = tabFornecedor.getSelectedRow();

        if (evt.getClickCount() > 1) {
            boolean consulta = true;
            viewDadosFornecedor insAlte = new viewDadosFornecedor(null, true, fornecedor, consulta);
            insAlte.setVisible(true);
            limparLab();
            listFornecedor.clear();
            listFornecedor.addAll(contFornecedor.listarTodos());
        } else {
            if (linha != -1) {
                fornecedor = new Fornecedor();
                fornecedor = listFornecedor.get(linha);
                labRazaoSocial.setText(fornecedor.getFornecedorRazaoSicial());
                labCidade.setText(fornecedor.getFornecedorCidade() + "  Estado:  " + fornecedor.getFornecedorEstado());
                labNomeContato.setText(fornecedor.getForncedorNomeContato());

                labCNPJ.setText(fornecedor.getFornecedorCNPJ());
                labNomeFantasia.setText(fornecedor.getFornecedorNomeFantasia());
                labEmail.setText(fornecedor.getFornecedorEmail());
                // labEstado.setText(fornecedor.getFornecedorEstado());

                labTelefone.setText(fornecedor.getFornecedorTelefoneCelular());
            }
        }
    }//GEN-LAST:event_tabFornecedorMouseClicked

    private void botVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVoltarActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_botVoltarActionPerformed

    private void botNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botNovoActionPerformed

        fornecedor = null;
        boolean consulta = false;
        // JOptionPane.showMessageDialog(null, funcionario);
        viewDadosFornecedor dadosFor = new viewDadosFornecedor(null, true, fornecedor, consulta);
        dadosFor.setVisible(true);
        listFornecedor.clear();
        listFornecedor.addAll(contFornecedor.listarTodos());
        limparLab();

        // TODO add your handling code here:
    }//GEN-LAST:event_botNovoActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased

        listFornecedor.clear();
        listFornecedor.addAll(contFornecedor.listarPorNome(txtBuscar.getText()));

        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                viewFornecedor dialog = new viewFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAlterar;
    private javax.swing.JButton botExcluir;
    private javax.swing.JButton botFechar;
    private javax.swing.JButton botLimpar;
    private javax.swing.JButton botNovo;
    private javax.swing.JButton botVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel labCNPJ;
    private javax.swing.JLabel labCidade;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labNomeContato;
    private javax.swing.JLabel labNomeFantasia;
    private javax.swing.JLabel labRazaoSocial;
    private javax.swing.JLabel labTelefone;
    private java.util.List<Fornecedor> listFornecedor;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente2;
    private rojerusan.RSPanelImage rSPanelImage1;
    private rojerusan.RSTableMetro tabFornecedor;
    private javax.swing.JTextField txtBuscar;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
private void limparLab() {
        labCidade.setText("");
        labNomeFantasia.setText("");
        labEmail.setText("");
        labCNPJ.setText("");
        labNomeContato.setText("");
        labEmail.setText("");
        //  labEstado.setText("____");

        labRazaoSocial.setText("");
        labTelefone.setText("");

    }

}
