/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Fornecedor;

import controle.ControleFornecedor;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicComboBoxUI;
import modelo.Fornecedor;
import static validacao.ValidaCampos.setMaxLength;

/**
 *
 * @author Maycon
 */
public class viewDadosFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form viewDadosFornecedor
     */
    Fornecedor fornecedor;
    ControleFornecedor contForne;
    boolean status;

    JComboBox comboBox_1 = new JComboBox();

    public viewDadosFornecedor(java.awt.Frame parent, boolean modal, Fornecedor forne, boolean consulta) {
        super(parent, modal);
        initComponents();
        editarTxts();

        validaCampos();
       txtRazaoSocial.requestFocus();
//       boxEstado.setUI(new BasicComboBoxUI() {
//            @Override
//	    protected JButton createArrowButton() {
//	        return new JButton() {
//	        	@Override
//	        	public Color getBackground() {		        		
//	        		return super.getBackground().WHITE;
//	        	}	
//	        	@Override
//	        	public Border getBorder() {
//	        		// TODO Auto-generated method stub
//	        		return javax.swing.BorderFactory.createLineBorder(new Color(255, 255, 255), -100);
//	        	}
//	        	
//                        @Override
//	            public int getWidth() {
//	                return 20;
//	            }
//	        };
//	    }   
//	});
       
       //pam.add(boxEstado);

        if (forne == null) {
            status = false;
            fornecedor = new Fornecedor();
            contForne = new ControleFornecedor();
        } else {
            status = true;
            fornecedor = forne;
            setarAlterar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneNome2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        botFechar3 = new javax.swing.JButton();
        panelDados = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        boxEstado = new javax.swing.JComboBox<>();
        txtNomeFantasia = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtNomeContato = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        formatTelefone = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEMail = new javax.swing.JTextField();
        txtCNPJ = new javax.swing.JTextField();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        botCancelar = new javax.swing.JButton();
        botSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        paneNome2.setBackground(new java.awt.Color(26, 35, 126));
        paneNome2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fornecedor");

        botFechar3.setBackground(new java.awt.Color(26, 35, 126));
        botFechar3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        botFechar3.setForeground(new java.awt.Color(255, 255, 255));
        botFechar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/fecharr24px.png"))); // NOI18N
        botFechar3.setContentAreaFilled(false);
        botFechar3.setOpaque(true);
        botFechar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botFechar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneNome2Layout = new javax.swing.GroupLayout(paneNome2);
        paneNome2.setLayout(paneNome2Layout);
        paneNome2Layout.setHorizontalGroup(
            paneNome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNome2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                .addComponent(botFechar3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        paneNome2Layout.setVerticalGroup(
            paneNome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNome2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5))
            .addComponent(botFechar3)
        );

        panelDados.setBackground(new java.awt.Color(255, 255, 255));
        panelDados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 53, 147)));
        panelDados.setEnabled(false);

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Razão Social:");

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Nome Fantásia:");

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("CNPJ:");

        jLabel10.setBackground(new java.awt.Color(204, 204, 255));
        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setText("Cidade:");

        jLabel11.setBackground(new java.awt.Color(204, 204, 255));
        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("ESTADO:");

        txtRazaoSocial.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        txtCidade.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        boxEstado.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        boxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        boxEstado.setBorder(null);

        txtNomeFantasia.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        txtNomeFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFantasiaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações Para Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 11))); // NOI18N

        txtNomeContato.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("Nome:");

        jLabel12.setBackground(new java.awt.Color(204, 204, 255));
        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setText("Telefone Celular:");

        try {
            formatTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatTelefone.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        jLabel16.setBackground(new java.awt.Color(204, 204, 255));
        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setText("Email:");

        txtEMail.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(89, 89, 89)
                        .addComponent(txtEMail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(formatTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 214, Short.MAX_VALUE))
                            .addComponent(txtNomeContato))))
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(formatTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEMail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        txtCNPJ.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
        panelDados.setLayout(panelDadosLayout);
        panelDadosLayout.setHorizontalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(25, 25, 25)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRazaoSocial)
                    .addComponent(txtNomeFantasia)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosLayout.createSequentialGroup()
                        .addComponent(txtCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCNPJ))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDadosLayout.setVerticalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(40, 53, 147));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(26, 35, 126));
        rSPanelGradiente1.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.HORIZONTAL);

        botCancelar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/cancel18px.png"))); // NOI18N
        botCancelar.setText("CANCELAR");
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });

        botSalvar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/salvar18px.png"))); // NOI18N
        botSalvar.setText("SALVAR");
        botSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(botCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botCancelar)
                    .addComponent(botSalvar))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneNome2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(paneNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botFechar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botFechar3ActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_botFechar3ActionPerformed

    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed

        //   fornecedor = null;
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_botCancelarActionPerformed

    private void botSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSalvarActionPerformed

        if (txtCNPJ.getText().equals("   .   .   -  ") || txtNomeFantasia.getText().isEmpty() || txtRazaoSocial.getText().isEmpty()
                || txtCidade.getText().isEmpty() || formatTelefone.getText().equals("(   )     -    ") || txtEMail.getText().isEmpty() || txtNomeFantasia.getText().isEmpty() || txtNomeContato.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "PREENCHER TODOS AS INFORMAÇÕES");
        } else {
            if (status == false) {
                List<Fornecedor> Email = contForne.buscarEmail(txtEMail.getText());
                if (Email.isEmpty()) {
                    fornecedor.setFornecedorRazaoSicial(txtRazaoSocial.getText());
                    fornecedor.setFornecedorNomeFantasia(txtNomeFantasia.getText());
                    fornecedor.setFornecedorCNPJ(txtCNPJ.getText());
                    fornecedor.setFornecedorCidade(txtCidade.getText());
                    fornecedor.setFornecedorEstado(boxEstado.getSelectedItem().toString());
                    fornecedor.setFornecedorTelefoneCelular(formatTelefone.getText());
                    fornecedor.setForncedorNomeContato(txtNomeContato.getText());
                    fornecedor.setFornecedorEmail(txtEMail.getText());
                    contForne.gravarNovo(fornecedor);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "FORNECEDOR JÁ CADASTRADO COM ESTE EMAIL");

                }
            } else {

                if(fornecedor.getFornecedorEmail().equals(txtEMail.getText())){
                    contForne = new ControleFornecedor();
                    fornecedor.setFornecedorRazaoSicial(txtRazaoSocial.getText());
                    fornecedor.setFornecedorNomeFantasia(txtNomeFantasia.getText());
                    fornecedor.setFornecedorCNPJ(txtCNPJ.getText());
                    fornecedor.setFornecedorCidade(txtCidade.getText());
                    fornecedor.setFornecedorEstado(boxEstado.getSelectedItem().toString());
                    fornecedor.setFornecedorTelefoneCelular(formatTelefone.getText());
                    fornecedor.setForncedorNomeContato(txtNomeContato.getText());
                    fornecedor.setFornecedorEmail(txtEMail.getText());
                    contForne.salvarAlteracao(fornecedor);
                    dispose();
                }else{
                    contForne = new ControleFornecedor();
                    List<Fornecedor> Email = contForne.buscarEmail(txtEMail.getText());
                    if(Email.isEmpty()){
                        fornecedor.setFornecedorRazaoSicial(txtRazaoSocial.getText());
                    fornecedor.setFornecedorNomeFantasia(txtNomeFantasia.getText());
                    fornecedor.setFornecedorCNPJ(txtCNPJ.getText());
                    fornecedor.setFornecedorCidade(txtCidade.getText());
                    fornecedor.setFornecedorEstado(boxEstado.getSelectedItem().toString());
                    fornecedor.setFornecedorTelefoneCelular(formatTelefone.getText());
                    fornecedor.setForncedorNomeContato(txtNomeContato.getText());
                    fornecedor.setFornecedorEmail(txtEMail.getText());
                    contForne.salvarAlteracao(fornecedor);
                    dispose();
                    }else{
                       JOptionPane.showMessageDialog(null, "FORNECEDOR JÁ CADASTRADO COM ESTE EMAIL"); 
                    }
                }
                
            }
        }
    }//GEN-LAST:event_botSalvarActionPerformed

    private void txtNomeFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFantasiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewDadosFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewDadosFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewDadosFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewDadosFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                viewDadosFornecedor dialog = new viewDadosFornecedor(new javax.swing.JFrame(), true, null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botCancelar;
    private javax.swing.JButton botFechar3;
    private javax.swing.JButton botSalvar;
    private javax.swing.JComboBox<String> boxEstado;
    private javax.swing.JFormattedTextField formatTelefone;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel paneNome2;
    private javax.swing.JPanel panelDados;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEMail;
    private javax.swing.JTextField txtNomeContato;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtRazaoSocial;
    // End of variables declaration//GEN-END:variables

    private void editarTxts() {
        txtCNPJ.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        formatTelefone.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
//        senhaConfirmar.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
//        senhaNova.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        txtNomeContato.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        txtCidade.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        txtEMail.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        txtNomeFantasia.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        txtRazaoSocial.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));

    }

    public Border getBorder() {
        return javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 102), 3);
    }

    @Override
    public Color getBackground() {
        return super.getBackground().WHITE;
    }
    
    
        private void setarAlterar() {
        txtNomeFantasia.setText(fornecedor.getFornecedorNomeFantasia());
        txtRazaoSocial.setText(fornecedor.getFornecedorRazaoSicial());
        txtCidade.setText(fornecedor.getFornecedorCidade());
        txtEMail.setText(fornecedor.getFornecedorEmail());
        txtNomeContato.setText(fornecedor.getForncedorNomeContato());
        boxEstado.setSelectedItem(fornecedor.getFornecedorEstado());
        txtCNPJ.setText(fornecedor.getFornecedorCNPJ());
        formatTelefone.setText(fornecedor.getFornecedorTelefoneCelular());
        
      
    }
        
        
       private void validaCampos(){
           setMaxLength(txtEMail, 45);
           setMaxLength(txtNomeFantasia, 45);
           setMaxLength(txtRazaoSocial, 45);
           setMaxLength(txtCidade, 45);
           setMaxLength(txtNomeContato, 45);
       }

}
