/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Login;

import controle.ControleCaixa;
import controle.ControleFuncionario;
import java.awt.Color;

import static java.lang.System.exit;
import java.util.List;
import javax.swing.BorderFactory;

import modelo.Caixa;

import modelo.Funcionario;
import view.Funcionario.viewDadosFuncionario;

import view.Fundamental.TelaIncialE;

import view.Fundamental.abrirCaixa.AbrirCaixa;

/**
 *
 * @author Maycon
 */
public class LoginSistema extends javax.swing.JDialog {

    /**
     * Creates new form LoginSistema
     */
    Funcionario funcionario;
    private Caixa cai = new Caixa();
    ControleCaixa contCaixa = new ControleCaixa();

    public LoginSistema(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ControleFuncionario conta = new ControleFuncionario();
        Funcionario f;
        long valor = conta.conta();
        if (valor == 0) {
            viewDadosFuncionario x = new viewDadosFuncionario(null, true, null, true, null);
            x.setVisible(true);
        } else {
            txtEmail.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
            txtSenha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
            jLabel1.requestFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        jLabel1 = new javax.swing.JLabel();
        botFechar = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botFechar1 = new javax.swing.JButton();
        botEntrar = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        labInvalido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        rSPanelGradiente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSPanelGradiente1.setColorPrimario(new java.awt.Color(204, 204, 255));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(204, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/personagem128px.png"))); // NOI18N

        botFechar.setBackground(new java.awt.Color(255, 0, 0));
        botFechar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botFechar.setForeground(new java.awt.Color(255, 255, 255));
        botFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/fechar34px.png"))); // NOI18N
        botFechar.setContentAreaFilled(false);
        botFechar.setFocusable(false);
        botFechar.setOpaque(true);
        botFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botFecharActionPerformed(evt);
            }
        });

        txtEmail.setBackground(new java.awt.Color(204, 204, 255));
        txtEmail.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        txtEmail.setText("DIGITE SEU EMAIL DE USUÁRIO");
        txtEmail.setBorder(null);
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/email24px.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/password24px.png"))); // NOI18N

        botFechar1.setBackground(new java.awt.Color(255, 0, 0));
        botFechar1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        botFechar1.setForeground(new java.awt.Color(255, 255, 255));
        botFechar1.setText("SAIR");
        botFechar1.setContentAreaFilled(false);
        botFechar1.setFocusable(false);
        botFechar1.setOpaque(true);
        botFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botFechar1ActionPerformed(evt);
            }
        });

        botEntrar.setBackground(new java.awt.Color(0, 0, 153));
        botEntrar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        botEntrar.setForeground(new java.awt.Color(255, 255, 255));
        botEntrar.setText("ENTRAR");
        botEntrar.setActionCommand("enter");
        botEntrar.setContentAreaFilled(false);
        botEntrar.setFocusable(false);
        botEntrar.setOpaque(true);
        botEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEntrarActionPerformed(evt);
            }
        });

        txtSenha.setBackground(new java.awt.Color(204, 204, 255));
        txtSenha.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        txtSenha.setText("DIGITE SUA SENHA");
        txtSenha.setToolTipText("");
        txtSenha.setBorder(null);
        txtSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSenhaMouseClicked(evt);
            }
        });

        labInvalido.setBackground(new java.awt.Color(255, 0, 0));
        labInvalido.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labInvalido.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                        .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botFechar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                    .addComponent(txtSenha))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(botFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(labInvalido)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addComponent(botFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labInvalido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(botEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(botFechar1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botFecharActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_botFecharActionPerformed

    private void botFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botFechar1ActionPerformed

        exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_botFechar1ActionPerformed

    private void botEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEntrarActionPerformed

        funcionario = new Funcionario();
        ControleFuncionario contFunc = new ControleFuncionario();
        if (contFunc.logarUsuario(txtEmail.getText(), txtSenha.getText())) {
            funcionario = contFunc.findAcha(txtEmail.getText(), txtSenha.getText());

            List<Caixa> caixa = contCaixa.buscar();

            contFunc.setUsuarioLogado(funcionario);

            if (caixa.isEmpty()) {
                AbrirCaixa abrirCai = new AbrirCaixa(null, true, funcionario);
                abrirCai.setVisible(true);
                dispose();
            } else {
                Funcionario funCaixaAberto = new Funcionario();
                funCaixaAberto = ControleFuncionario.getUsuarioLogado();              
                contCaixa.setCaixa(caixa.get(0));
                TelaIncialE telaIn = new TelaIncialE(funcionario);
                telaIn.setVisible(true);
                dispose();
            }
        } else {
            labInvalido.setText("EMAIL E SENHA INVALIDADO!!");
            txtEmail.setText("");
            txtSenha.setText("");
            txtEmail.requestFocus();
            txtSenha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.RED));
            txtEmail.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.RED));
            txtEmail.requestFocus();
        }

//        if (funcionario == null) {
//
//
//        } else {
//
//            List<Caixa> caixa = contCaixa.buscar();
//            
//            
//            if (caixa.isEmpty()) {
//                AbrirCaixa abrirCai = new AbrirCaixa(null, true, funcionario);
//                abrirCai.setVisible(true);
//            } else {
//        
//            }
//
//            TelaIncial login = new TelaIncial(funcionario);
//            login.setVisible(true);
//            dispose();
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_botEntrarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked

        txtEmail.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenhaMouseClicked

        txtSenha.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginSistema dialog = new LoginSistema(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botEntrar;
    private javax.swing.JButton botFechar;
    private javax.swing.JButton botFechar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labInvalido;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
