/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Funcionario;

import controle.ControleFuncionario;
import java.awt.Color;

import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Funcionario;
import validacao.ValidaCPF;
import static validacao.ValidaCampos.setMaxLength;

/**
 *
 * @author Maycon
 */
public class viewDadosFuncionario extends javax.swing.JDialog {

    /**
     * Creates new form viewDadosFuncionario
     */
    Funcionario funcionario;
    ControleFuncionario contFuncionario = new ControleFuncionario();
    boolean status;

    Funcionario alteraCargo;

    public viewDadosFuncionario(java.awt.Frame parent, boolean modal, Funcionario fun, boolean consulta, Funcionario funci) {
        super(parent, modal);
        initComponents();
        validaCampos();

        status = consulta;
        funcionario = fun;
        alteraCargo = funci;
        if(fun==null &&funci==null){
            boxCargoFuncionario.setSelectedIndex(1);
            boxCargoFuncionario.setEnabled(false);
            status = false;
            funcionario = new Funcionario();
            editarTxts();
            botCancelar.setVisible(false);
            botFechar1.setVisible(false);
          //  JOptionPane.showMessageDialog(null, "AQUI");
        }else{

        if (fun.getFuncionarioCargo().equals("GERENTE") && funci == null) {
          status = consulta;
        } else if (fun.getFuncionarioCargo().equals("GERENTE")) {
            setarAlterar();
        } else {
            setarAlterar();
            boxCargoFuncionario.setEnabled(false);
        }
        editarTxts();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneNome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botFechar1 = new javax.swing.JButton();
        panelDados = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        txtNomeDeRua = new javax.swing.JTextField();
        txtBairroFuncionario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumeroRua = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        boxEstado = new javax.swing.JComboBox<>();
        formatCPF = new javax.swing.JFormattedTextField();
        formatTelefone = new javax.swing.JFormattedTextField();
        dateDataNascimento = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        panelLogin = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        senhaNova = new javax.swing.JPasswordField();
        senhaConfirmar = new javax.swing.JPasswordField();
        boxCargoFuncionario = new javax.swing.JComboBox<>();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        botCancelar = new javax.swing.JButton();
        botSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        paneNome.setBackground(new java.awt.Color(26, 35, 126));
        paneNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Funcionário");

        botFechar1.setBackground(new java.awt.Color(26, 35, 126));
        botFechar1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        botFechar1.setForeground(new java.awt.Color(255, 255, 255));
        botFechar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/fecharr24px.png"))); // NOI18N
        botFechar1.setContentAreaFilled(false);
        botFechar1.setOpaque(true);
        botFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botFechar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneNomeLayout = new javax.swing.GroupLayout(paneNome);
        paneNome.setLayout(paneNomeLayout);
        paneNomeLayout.setHorizontalGroup(
            paneNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(botFechar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        paneNomeLayout.setVerticalGroup(
            paneNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3))
            .addComponent(botFechar1)
        );

        panelDados.setBackground(new java.awt.Color(255, 255, 255));
        panelDados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 53, 147)));
        panelDados.setEnabled(false);

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Nome:");

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Data de Nascimento:");

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("CPF:");

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Rua:");

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("Cidade:");

        jLabel10.setBackground(new java.awt.Color(204, 204, 255));
        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setText("ESTADO:");

        jLabel12.setBackground(new java.awt.Color(204, 204, 255));
        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setText("Telefone Celular:");

        jLabel13.setBackground(new java.awt.Color(204, 204, 255));
        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setText("Bairro:");

        txtNomeFuncionario.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        txtNomeDeRua.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        txtBairroFuncionario.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("Nº:");

        txtNumeroRua.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        txtCidade.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        boxEstado.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        boxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        boxEstado.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        try {
            formatCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatCPF.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        try {
            formatTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatTelefone.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        dateDataNascimento.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        dateDataNascimento.setMaxSelectableDate(new java.util.Date(253370775705000L));

        jLabel14.setBackground(new java.awt.Color(204, 204, 255));
        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setText("CARGO:");

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabel11.setBackground(new java.awt.Color(204, 204, 255));
        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("E-mail: *");

        txtEmail.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("INFORMAÇÕES PARA LOGIN");

        jLabel16.setBackground(new java.awt.Color(204, 204, 255));
        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setText("Senha: *");

        jLabel17.setBackground(new java.awt.Color(204, 204, 255));
        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setText("Confirma Senha: *");

        senhaNova.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        senhaNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaNovaActionPerformed(evt);
            }
        });

        senhaConfirmar.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(15, 15, 15)
                        .addComponent(txtEmail))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(13, 13, 13)
                        .addComponent(senhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(senhaConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        boxCargoFuncionario.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        boxCargoFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATENDENTE", "GERENTE" }));
        boxCargoFuncionario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boxCargoFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boxCargoFuncionario.setOpaque(false);

        javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
        panelDados.setLayout(panelDadosLayout);
        panelDadosLayout.setHorizontalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosLayout.createSequentialGroup()
                                .addComponent(formatTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelDadosLayout.createSequentialGroup()
                                .addComponent(txtNomeDeRua)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNumeroRua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxCargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosLayout.createSequentialGroup()
                                .addComponent(txtCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtBairroFuncionario))
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeFuncionario)
                            .addGroup(panelDadosLayout.createSequentialGroup()
                                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(formatCPF))
                                .addGap(0, 246, Short.MAX_VALUE)))))
                .addContainerGap())
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDadosLayout.setVerticalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(dateDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(formatCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(boxCargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNomeDeRua, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtNumeroRua, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtBairroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(formatTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        rSPanelGradiente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSPanelGradiente1.setColorPrimario(new java.awt.Color(40, 53, 147));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(26, 35, 126));
        rSPanelGradiente1.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.HORIZONTAL);

        botCancelar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/cancel18px.png"))); // NOI18N
        botCancelar.setText("CANCELAR");
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });

        botSalvar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/salvar18px.png"))); // NOI18N
        botSalvar.setText("SALVAR");
        botSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(botCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botCancelar)
                    .addComponent(botSalvar))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(paneNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botFechar1ActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_botFechar1ActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void senhaNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaNovaActionPerformed

    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed

        funcionario = null;
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_botCancelarActionPerformed

    private void botSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSalvarActionPerformed

        if (formatCPF.getText().equals("   .   .   -  ") || txtBairroFuncionario.getText().isEmpty() || txtNomeFuncionario.getText().isEmpty()
                || txtCidade.getText().isEmpty() || txtNumeroRua.getText().isEmpty() || formatTelefone.getText().equals("(   )     -    ") || dateDataNascimento.getDate() == null || txtNomeDeRua.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "PREENCHER TODOS AS INFORMAÇÕES");
        } else {
            if (status == false) {
                funcionario = new Funcionario();
                funcionario.setFuncionarioBairo(txtBairroFuncionario.getText());
                funcionario.setFuncionarioNome(txtNomeFuncionario.getText());
                funcionario.setFuncionarioCidade(txtCidade.getText());
                funcionario.setFuncionarioRua(txtNomeDeRua.getText());
                try{
                funcionario.setFuncionarioNumeroRua(Integer.parseInt(txtNumeroRua.getText()));
                funcionario.setFuncionarioTelefone(formatTelefone.getText());
                funcionario.setFuncionarioEstado(boxEstado.getSelectedItem().toString());
                funcionario.setFuncionarioDataNascimento(dateDataNascimento.getDate());
                funcionario.setFuncionarioCargo(boxCargoFuncionario.getSelectedItem().toString());
                if (!formatCPF.getText().equals("   .   .   -  ")) {
                    String cpf = formatCPF.getText();
                    cpf = cpf.replace(".", "");
                    cpf = cpf.replace("-", "");
                    if (!ValidaCPF.isCPF(cpf)) {
                        JOptionPane.showMessageDialog(null, "O CPF: " + formatCPF.getText() + " é invalido");
                        formatCPF.requestFocus();
                        formatCPF.setValue("");
                    } else {
                        List<Funcionario> CPF = contFuncionario.CPFIgual(formatCPF.getText());
                        //JOptionPane.showMessageDialog(null, CPF);
                        if (!CPF.isEmpty()) {
                            JOptionPane.showMessageDialog(null, "CPF JÁ CADASTRADO");
                        } else {
                            funcionario.setFuncionarioCPF(formatCPF.getText());

                            if (senhaNova.getText().equals(senhaConfirmar.getText())) {
                                funcionario.setFuncionarioSenha(senhaNova.getText());
                                List<Funcionario> nome = contFuncionario.buscarEmail(txtEmail.getText());
                                //JOptionPane.showMessageDialog(null, nome);
                                if (!nome.isEmpty()) {
                                    JOptionPane.showMessageDialog(null, "EMAIL JÁ CADASTRADO");
                                } else {
                                    if (txtEmail.getText().trim().isEmpty()) {

                                        JOptionPane.showMessageDialog(null, "Preencha todos os Campos com '*'");
                                    } else {
                                        if (senhaNova.getText().length() > 0) {
                                            funcionario.setFuncionarioEmail(txtEmail.getText());
                                            contFuncionario.gravarNovo(funcionario);

                                            dispose();
                                        } else {
                                            JOptionPane.showMessageDialog(null, "Preencha todos os Campos com '*'");
                                        }
                                    }

                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "As Senhas Não São Iguais");
                            }
                        }
                    }
                }
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Preencha o compo Nº com Numero");
                }
            } else {
            //    JOptionPane.showMessageDialog(null, "alterar");
                if (formatCPF.getText().equals("   .   .   -  ") || txtBairroFuncionario.getText().isEmpty() || txtNomeFuncionario.getText().isEmpty()
                        || txtCidade.getText().isEmpty() || txtNumeroRua.getText().isEmpty() || formatTelefone.getText().equals("(   )     -    ") || dateDataNascimento.getDate() == null || txtNomeDeRua.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "PREENCHER TODOS AS INFORMAÇÕES");
                } else {
                    alteraCargo.setFuncionarioBairo(txtBairroFuncionario.getText());
                    alteraCargo.setFuncionarioNome(txtNomeFuncionario.getText());
                    alteraCargo.setFuncionarioCidade(txtCidade.getText());
                    alteraCargo.setFuncionarioTelefone(formatTelefone.getText());
                    alteraCargo.setFuncionarioEstado(boxEstado.getSelectedItem().toString());
                    alteraCargo.setFuncionarioDataNascimento(dateDataNascimento.getDate());
                    alteraCargo.setFuncionarioCargo(boxCargoFuncionario.getSelectedItem().toString());
                    alteraCargo.setFuncionarioRua(txtNomeDeRua.getText());
                    try{
                    alteraCargo.setFuncionarioNumeroRua(Integer.parseInt(txtNumeroRua.getText()));
                    if (!formatCPF.getText().equals("   .   .   -  ")) {
                        String cpf = formatCPF.getText();
                        cpf = cpf.replace(".", "");
                        cpf = cpf.replace("-", "");

                        if (!ValidaCPF.isCPF(cpf)) {
                            JOptionPane.showMessageDialog(null, "O CPF: " + formatCPF.getText() + " é invalido");
                            formatCPF.requestFocus();
                            formatCPF.setValue("");
                        } else {

                            if (alteraCargo.getFuncionarioCPF().equals(formatCPF.getText())) {
                                alteraCargo.setFuncionarioCPF(formatCPF.getText());
                                if (senhaNova.getText().equals(senhaConfirmar.getText())) {
                                    alteraCargo.setFuncionarioSenha(senhaNova.getText());
                                    if (alteraCargo.getFuncionarioEmail().equals(txtEmail.getText())) {
                                        alteraCargo.setFuncionarioEmail(txtEmail.getText());
                                        if (senhaNova.getText().length() > 0 || senhaConfirmar.getText().length() > 0) {
                                            contFuncionario.salvarAlteracao(alteraCargo);
                                            dispose();
                                        } else {
                                            JOptionPane.showMessageDialog(null, "Preencha todos os Campos com '*'");
                                        }
                                    } else {
                                        List<Funcionario> nome = contFuncionario.buscarEmail(txtEmail.getText());
                                        if (nome.isEmpty()) {
                                            if (txtEmail.getText().trim().isEmpty()) {
                                                JOptionPane.showMessageDialog(null, "Preencha todos os Campos com '*'");
                                            } else {
                                                if (senhaNova.getText().length() > 0 || senhaConfirmar.getText().length() > 0) {
                                                    alteraCargo.setFuncionarioEmail(txtEmail.getText());
                                                    contFuncionario.salvarAlteracao(alteraCargo);
                                                    dispose();
                                                } else {
                                                    JOptionPane.showMessageDialog(null, "Preencha todos os Campos com '*'");
                                                }
                                            }
                                        } else {
                                            JOptionPane.showMessageDialog(null, "EMAIL JÁ CADASTRADO");
                                        }

                                    }

                                } else {
                                    JOptionPane.showMessageDialog(null, "As Senhas Não São Iguais");
                                }
                            } else {
                                
                                
                                List<Funcionario> CPF = contFuncionario.CPFIgual(formatCPF.getText());
                                if (CPF.isEmpty()) {
                                    alteraCargo.setFuncionarioCPF(formatCPF.getText());
                                    if (senhaNova.getText().equals(senhaConfirmar.getText())) {
                                        alteraCargo.setFuncionarioSenha(senhaNova.getText());
                                        if (alteraCargo.getFuncionarioEmail().equals(txtEmail.getText())) {
                                            alteraCargo.setFuncionarioEmail(txtEmail.getText());
                                            if (senhaNova.getText().length() > 0 || senhaConfirmar.getText().length() > 0) {
                                                contFuncionario.salvarAlteracao(alteraCargo);
                                                dispose();
                                            } else {
                                                JOptionPane.showMessageDialog(null, "Preencha todos os Campos com '*'");
                                            }
                                        } else {
                                            List<Funcionario> nome = contFuncionario.buscarEmail(txtEmail.getText());
                                            if (nome.isEmpty()) {
                                                if (txtEmail.getText().trim().isEmpty()) {
                                                    JOptionPane.showMessageDialog(null, "Preencha todos os Campos com '*'");
                                                } else {
                                                    if (senhaNova.getText().length() > 0 || senhaConfirmar.getText().length() > 0) {
                                                        alteraCargo.setFuncionarioEmail(txtEmail.getText());
                                                        contFuncionario.salvarAlteracao(alteraCargo);
                                                        dispose();
                                                    } else {
                                                        JOptionPane.showMessageDialog(null, "Preencha todos os Campos com '*'");
                                                    }
                                                }
                                            } else {
                                                JOptionPane.showMessageDialog(null, "EMAIL JÁ CADASTRADO");
                                            }

                                        }

                                    } else {
                                        JOptionPane.showMessageDialog(null, "As Senhas Não São Iguais");
                                    }
                                }
                            }
                        }
                    }
                    }catch(NumberFormatException e){
                        JOptionPane.showMessageDialog(null, "Preencha o compo Nº com Numero");
                    }
                }
                
            }
        }
    //    JOptionPane.showMessageDialog(null, funcionario.getFuncionarioCargo());
    }//GEN-LAST:event_botSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewDadosFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewDadosFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewDadosFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewDadosFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                viewDadosFuncionario dialog = new viewDadosFuncionario(new javax.swing.JFrame(), true, null, true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botCancelar;
    private javax.swing.JButton botFechar1;
    private javax.swing.JButton botSalvar;
    private javax.swing.JComboBox<String> boxCargoFuncionario;
    private javax.swing.JComboBox<String> boxEstado;
    private com.toedter.calendar.JDateChooser dateDataNascimento;
    private javax.swing.JFormattedTextField formatCPF;
    private javax.swing.JFormattedTextField formatTelefone;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel paneNome;
    private javax.swing.JPanel panelDados;
    private javax.swing.JPanel panelLogin;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private javax.swing.JPasswordField senhaConfirmar;
    private javax.swing.JPasswordField senhaNova;
    private javax.swing.JTextField txtBairroFuncionario;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeDeRua;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtNumeroRua;
    // End of variables declaration//GEN-END:variables

    private void editarTxts() {
        formatCPF.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        formatTelefone.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        senhaConfirmar.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        senhaNova.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        txtBairroFuncionario.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        txtCidade.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        txtEmail.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        txtNomeFuncionario.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        txtNomeDeRua.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        txtNumeroRua.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        boxCargoFuncionario.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, Color.BLACK));
        boxEstado.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, Color.BLACK));
        //boxEstado.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
    }

    private void setarAlterar() {
        txtBairroFuncionario.setText(alteraCargo.getFuncionarioBairo());
        txtNomeFuncionario.setText(alteraCargo.getFuncionarioNome());
        txtCidade.setText(alteraCargo.getFuncionarioCidade());
        txtEmail.setText(alteraCargo.getFuncionarioEmail());
        txtNomeDeRua.setText(alteraCargo.getFuncionarioRua());
        txtNumeroRua.setText(String.valueOf(alteraCargo.getFuncionarioNumeroRua()));
        formatCPF.setText(alteraCargo.getFuncionarioCPF());
        formatTelefone.setText(alteraCargo.getFuncionarioTelefone());
        boxEstado.setSelectedItem(alteraCargo.getFuncionarioEstado());
        dateDataNascimento.setDate(alteraCargo.getFuncionarioDataNascimento());
        senhaNova.setText(alteraCargo.getFuncionarioSenha());
        senhaConfirmar.setText(alteraCargo.getFuncionarioSenha());
        boxCargoFuncionario.setSelectedItem(alteraCargo.getFuncionarioCargo());
    }
//
//    private void pegarTela() {
//        if (status == false) {
//            funcionario.setFuncionarioBairo(txtBairroFuncionario.getText());
//            funcionario.setFuncionarioNome(txtNomeFuncionario.getText());
//            funcionario.setFuncionarioCidade(txtCidade.getText());
//            funcionario.setFuncionarioEmail(txtEmail.getText());
//            funcionario.setFuncionarioRua(txtNomeDeRua.getText());
//            funcionario.setFuncionarioNumeroRua(Integer.parseInt(txtNumeroRua.getText()));
//            if (!formatCPF.getText().equals("   .   .   -  ")) {
//                String cpf = formatCPF.getText();
//                cpf = cpf.replace(".", "");
//                cpf = cpf.replace("-", "");
//                if (!ValidaCPF.isCPF(cpf)) {
//                    JOptionPane.showMessageDialog(null, "O CPF: " + formatCPF.getText() + " é invalido");
//                    formatCPF.requestFocus();
//                    formatCPF.setValue("");
//                } else {
//                    funcionario.setFuncionarioCPF(formatCPF.getText());
//                    funcionario.setFuncionarioTelefone(formatTelefone.getText());
//                    funcionario.setFuncionarioEstado(boxEstado.getSelectedItem().toString());
//                    funcionario.setFuncionarioDataNascimento(dateDataNascimento.getDate());
//                    funcionario.setFuncionarioCargo(boxCargoFuncionario.getSelectedItem().toString());
//                    if (senhaNova.getText().equals(senhaConfirmar.getText())) {
//                        funcionario.setFuncionarioSenha(senhaNova.getText());
//                        if (txtEmail.getText().trim().isEmpty()) {
//
//                            JOptionPane.showMessageDialog(null, "Preencha todos os Campos com '*'");
//                        } else {
//                            if (senhaNova.getText().length() > 0) {
//                                contFuncionario.gravarNovo(funcionario);
//                                dispose();
//                            } else {
//                                JOptionPane.showMessageDialog(null, "Preencha todos os Campos com '*'");
//                            }
//                        }
//                    } else {
//                        JOptionPane.showMessageDialog(null, "As Senhas Não São Iguais");
//                    }
//                }
//            }
//        }
//
//    }

    private void editar() {
        panelDados.setEnabled(false);

        txtBairroFuncionario.setEditable(false);
        txtBairroFuncionario.setBackground(Color.WHITE);
        txtNomeFuncionario.setEditable(false);
        txtNomeFuncionario.setBackground(Color.WHITE);
        txtCidade.setEditable(false);
        txtCidade.setBackground(Color.WHITE);
        txtEmail.setEditable(false);
        txtEmail.setBackground(Color.WHITE);
        txtNomeDeRua.setEditable(false);
        txtNomeDeRua.setBackground(Color.WHITE);
        txtNumeroRua.setEditable(false);
        txtNumeroRua.setBackground(Color.WHITE);
        formatCPF.setEditable(false);
        formatCPF.setBackground(Color.WHITE);
        formatTelefone.setEditable(false);
        formatTelefone.setBackground(Color.WHITE);
        boxEstado.setEnabled(false);
        boxEstado.setBackground(Color.WHITE);
        boxCargoFuncionario.setEnabled(false);
        boxCargoFuncionario.setBackground(Color.WHITE);
        dateDataNascimento.setEnabled(false);
        dateDataNascimento.setBackground(Color.WHITE);
//        senhaNova.setText(cliente.getFuncionarioSenha());
//        senhaConfirmar.setText(cliente.getFuncionarioSenha());
        formatCPF.setEditable(false);
        formatCPF.setBackground(Color.WHITE);
        senhaNova.setEditable(false);
        senhaNova.setBackground(Color.WHITE);
        senhaConfirmar.setEditable(false);
        senhaConfirmar.setBackground(Color.WHITE);
        editarTxts();
    }

    private void validaCampos() {
        setMaxLength(txtEmail, 45);
        setMaxLength(txtBairroFuncionario, 25);
        setMaxLength(txtCidade, 45);

        setMaxLength(txtNomeDeRua, 45);
        setMaxLength(txtNomeFuncionario, 45);
    }

}
