/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Fundamental.Conta;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Locale;
import modelo.Pagamento;

/**
 *
 * @author Maycon
 */
public class MostrarContaPaga extends javax.swing.JDialog {

    /**
     * Creates new form MostrarContaPaga
     */
    private SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/yyyy");

    public MostrarContaPaga(java.awt.Frame parent, boolean modal, Pagamento pag) {
        super(parent, modal);
        initComponents();
        labConta.setText("CONTA " + pag.getDescricao());
        if (pag.getJuros() != 0 && pag.getDesconto() == 0) {

            labDataVencimento.setText("Data de Vencimento: " + formatar.format(pag.getDataVencimento())+".");
            labPagamento.setText("Data Pagamento: " + formatar.format(pag.getDataPaga()) + ".");
            labValorConta.setText("Valor da Conta: " + doubleString(pag.getValorPagar() - pag.getJuros()) + ".");
            labInformacoesAdicionais.setText("Juros no valor de R$:" + doubleString(pag.getJuros()) + ".");
            labValorPago.setText("Valor total de R$:" + doubleString(pag.getValorPagar()) + ".");

        } else if (pag.getJuros() == 0 && pag.getDesconto() != 0) {

            labDataVencimento.setText("Data de Vencimento: " + formatar.format(pag.getDataVencimento())+".");
            labPagamento.setText("Data Pagamento: " + formatar.format(pag.getDataPaga()) + ".");
            labValorConta.setText("Valor da Conta: " + doubleString(pag.getValorPagar() + pag.getDesconto()) + ".");
            labInformacoesAdicionais.setText("Desconto no valor de R$:" + doubleString(pag.getDesconto()) + ".");
            labValorPago.setText("Valor Total de R$:" + doubleString(pag.getValorPagar()) + ".");
        }else if(pag.getJuros() != 0 && pag.getDesconto() != 0){
            labDataVencimento.setText("Data de Vencimento: " + formatar.format(pag.getDataVencimento())+".");
            labPagamento.setText("Data Pagamento: " + formatar.format(pag.getDataPaga()) + ".");
            labValorConta.setText("Valor da Conta: " + doubleString(pag.getValorPagar() + pag.getDesconto()) + ".");
            labInformacoesAdicionais.setText("Desconto no valor de R$:" + doubleString(pag.getDesconto()) + ".  E Juros no valor de R$:"+doubleString(pag.getJuros())+".");
            labValorPago.setText("Valor Total de R$:" + doubleString(pag.getValorPagar()) + ".");
        } else {
            
            labDataVencimento.setText("Data de Vencimento: " + formatar.format(pag.getDataVencimento()));
            labPagamento.setText("Data Pagamento: " + formatar.format(pag.getDataPaga()) + ".");
            labValorConta.setText("Valor da Conta: " + doubleString(pag.getValorPagar()) + ".");
            labInformacoesAdicionais.setText("Valor Total de R$:" + doubleString(pag.getValorPagar()) + ".");
          //  labValorPago.setText("Fazendo está conta ser paga no valor total de R$:" + doubleString(pag.getValorPagar()) + ".");

        }
        //("  A data de Vencimento desta conta foi no dia: "+ formatar.format(pag.getDataVencimento())+", sendo\n efetuado o seu pagamento na data: "+formatar.format(pag.getDataPaga())+".\n"+
        //        "   O valor da conta é de R$:"+ doubleString(pag.getValorPagar()-pag.getJuros())+" tendo um acressimo de juros\n no valor de R$:"+doubleString(pag.getJuros())+"fazendo assim está conta ser paga no valor total de R$:"+doubleString(pag.getValorPagar())+".");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        paneNome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botFechar1 = new javax.swing.JButton();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        botCancelar = new javax.swing.JButton();
        labConta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labDataVencimento = new javax.swing.JLabel();
        labPagamento = new javax.swing.JLabel();
        labValorConta = new javax.swing.JLabel();
        labInformacoesAdicionais = new javax.swing.JLabel();
        labValorPago = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        paneNome.setBackground(new java.awt.Color(26, 35, 126));
        paneNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTA PAGA");

        botFechar1.setBackground(new java.awt.Color(26, 35, 126));
        botFechar1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        botFechar1.setForeground(new java.awt.Color(255, 255, 255));
        botFechar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/fecharr24px.png"))); // NOI18N
        botFechar1.setContentAreaFilled(false);
        botFechar1.setOpaque(true);
        botFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botFechar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneNomeLayout = new javax.swing.GroupLayout(paneNome);
        paneNome.setLayout(paneNomeLayout);
        paneNomeLayout.setHorizontalGroup(
            paneNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(botFechar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        paneNomeLayout.setVerticalGroup(
            paneNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3))
            .addComponent(botFechar1)
        );

        rSPanelGradiente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSPanelGradiente1.setColorPrimario(new java.awt.Color(40, 53, 147));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(26, 35, 126));
        rSPanelGradiente1.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.HORIZONTAL);

        botCancelar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/voltar18px.png"))); // NOI18N
        botCancelar.setText("VOLTAR");
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(botCancelar)
                .addContainerGap(394, Short.MAX_VALUE))
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(botCancelar)
                .addGap(2, 2, 2))
        );

        labConta.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações da conta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N

        labDataVencimento.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        labPagamento.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        labValorConta.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        labInformacoesAdicionais.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        labValorPago.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labInformacoesAdicionais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labDataVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labValorConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labValorPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(labDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labValorConta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labInformacoesAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(paneNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labConta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botFechar1ActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_botFechar1ActionPerformed

    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_botCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarContaPaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarContaPaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarContaPaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarContaPaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MostrarContaPaga dialog = new MostrarContaPaga(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botCancelar;
    private javax.swing.JButton botFechar1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labConta;
    private javax.swing.JLabel labDataVencimento;
    private javax.swing.JLabel labInformacoesAdicionais;
    private javax.swing.JLabel labPagamento;
    private javax.swing.JLabel labValorConta;
    private javax.swing.JLabel labValorPago;
    private javax.swing.JPanel paneNome;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    // End of variables declaration//GEN-END:variables

    public String doubleString(double d) {

        Locale.setDefault(new Locale("pt", "BR"));
        DecimalFormat df = new DecimalFormat("#,##0.00", new DecimalFormatSymbols(new Locale("pt", "BR")));
        String s = df.format(d);
        return s;
    }

}
