/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Cliente;

import controle.ControleCliente;
import controle.IntegridadeException;
import controle.NaoExisteException;
import java.awt.Color;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

import modelo.Cliente;
import static org.jdesktop.observablecollections.ObservableCollections.observableList;

/**
 *
 * @author Maycon
 */
public class viewCliente extends javax.swing.JDialog {

    /**
     * Creates new form viewCliente
     */
    Cliente cliente;
    ControleCliente contCliente;
    SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/yyyy");
    private boolean status = false;

    public viewCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //    tabFuncionario.
        //tabFuncionario.setColorFilasBackgound1(tabFuncionario.setValueAt(string, 1, 2));
        contCliente = new ControleCliente();
        listCliente.addAll(contCliente.listarTodos());
        tabFuncionario.setDefaultEditor(Object.class, null);
        txtBuscar.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE));

        tabFuncionario.getColumnModel().getColumn(0).setPreferredWidth(230);
        tabFuncionario.getColumnModel().getColumn(1).setPreferredWidth(30);
        tabFuncionario.getColumnModel().getColumn(2).setPreferredWidth(20);
        txtBuscar.requestFocus();
        //tabFuncionario.getColumnModel().getColumn(2).getCellRenderer();//setPreferredWidth(20); 
        ///   tabFuncionario.getColumn().setPreferredWidth(  ) ;
        //  tabFuncionario.setAutoResizeMode( tabFuncionario.AUTO_RESIZE_OFF );
//       JTableHeader header = tabFuncionario.getTableHeader();   
//    header.setPreferredSize(new Dimension(0, 50)); 
        //  DefaultTableCellRenderer rendererEsquerda = new DefaultTableCellRenderer(); 
        //  DefaultTableCellRenderer rendererCentro = new DefaultTableCellRenderer();
//    rendererEsquerda.setHorizontalAlignment(SwingConstants.LEFT);  
// tabFuncionario.getColumn(0).setMaxWidth(50);  
//    tabFuncionario.getColumn(1).setCellRenderer(rendererEsquerda); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listCliente =  observableList(new ArrayList<>());
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botFechar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        rSPanelGradiente2 = new rspanelgradiente.RSPanelGradiente();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        labelNome = new javax.swing.JLabel();
        labDataNasc = new javax.swing.JLabel();
        labCidades = new javax.swing.JLabel();
        labCPF = new javax.swing.JLabel();
        labBairro = new javax.swing.JLabel();
        laBNomeRua = new javax.swing.JLabel();
        labTelefone = new javax.swing.JLabel();
        labEmail = new javax.swing.JLabel();
        botAlterar = new javax.swing.JButton();
        botExcluir = new javax.swing.JButton();
        labRG = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        txtBuscar = new javax.swing.JTextField();
        botLimpar = new javax.swing.JButton();
        boxPesquisa = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabFuncionario = new rojerusan.RSTableMetro();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        botVoltar = new javax.swing.JButton();
        botNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(26, 35, 126));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cliente");

        botFechar.setBackground(new java.awt.Color(26, 35, 126));
        botFechar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botFechar.setForeground(new java.awt.Color(255, 255, 255));
        botFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/close.png"))); // NOI18N
        botFechar.setContentAreaFilled(false);
        botFechar.setOpaque(true);
        botFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2))
            .addComponent(botFechar)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        rSPanelGradiente2.setColorPrimario(new java.awt.Color(26, 35, 126));
        rSPanelGradiente2.setColorSecundario(new java.awt.Color(103, 58, 183));
        rSPanelGradiente2.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.VERTICAL);
        rSPanelGradiente2.setPreferredSize(new java.awt.Dimension(336, 135));

        rSPanelImage1.setBackground(new java.awt.Color(153, 153, 153));
        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imagem/asfalt-light.png"))); // NOI18N
        rSPanelImage1.setPreferredSize(new java.awt.Dimension(336, 135));

        labelNome.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelNome.setForeground(new java.awt.Color(255, 255, 255));
        labelNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/person.png"))); // NOI18N

        labDataNasc.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labDataNasc.setForeground(new java.awt.Color(255, 255, 255));
        labDataNasc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/calendario24px.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelImage1Layout.createSequentialGroup()
                        .addComponent(labDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labelNome)
                .addGap(18, 18, 18)
                .addComponent(labDataNasc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rSPanelGradiente2Layout = new javax.swing.GroupLayout(rSPanelGradiente2);
        rSPanelGradiente2.setLayout(rSPanelGradiente2Layout);
        rSPanelGradiente2Layout.setHorizontalGroup(
            rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );
        rSPanelGradiente2Layout.setVerticalGroup(
            rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente2Layout.createSequentialGroup()
                .addComponent(rSPanelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        labCidades.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labCidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/position.png"))); // NOI18N

        labCPF.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labCPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/card.png"))); // NOI18N

        labBairro.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        laBNomeRua.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        labTelefone.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/phone.png"))); // NOI18N

        labEmail.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/mail.png"))); // NOI18N

        botAlterar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/edit18px.png"))); // NOI18N
        botAlterar.setText("ALTERAR");
        botAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAlterarActionPerformed(evt);
            }
        });

        botExcluir.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/delete18px.png"))); // NOI18N
        botExcluir.setText("EXCLUIR");
        botExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botExcluirActionPerformed(evt);
            }
        });

        labRG.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labRG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/card.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelGradiente2, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botExcluir))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(laBNomeRua, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addGap(39, 39, 39))
                            .addComponent(labTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(labEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(labCPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labRG)
                                .addGap(125, 125, 125))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(labCidades, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(rSPanelGradiente2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labRG)
                    .addComponent(labCPF))
                .addGap(24, 24, 24)
                .addComponent(labCidades)
                .addGap(24, 24, 24)
                .addComponent(labBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(laBNomeRua, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(labTelefone)
                .addGap(24, 24, 24)
                .addComponent(labEmail)
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botExcluir)
                    .addComponent(botAlterar))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel1.setDoubleBuffered(false);
        kGradientPanel1.setkEndColor(new java.awt.Color(26, 35, 126));
        kGradientPanel1.setkStartColor(new java.awt.Color(40, 53, 147));

        txtBuscar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar.setOpaque(false);
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        botLimpar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/limpar18px.png"))); // NOI18N
        botLimpar.setText("LIMPAR");
        botLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimparActionPerformed(evt);
            }
        });

        boxPesquisa.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        boxPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOME", "CPF" }));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boxPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botLimpar)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(boxPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botLimpar))
                .addGap(10, 10, 10))
        );

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabFuncionario.setAutoCreateRowSorter(true);
        tabFuncionario.setBackground(new java.awt.Color(250, 250, 250));
        tabFuncionario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tabFuncionario.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tabFuncionario.setAutoscrolls(false);
        tabFuncionario.setColorBackgoundHead(new java.awt.Color(250, 250, 250));
        tabFuncionario.setColorFilasBackgound1(new java.awt.Color(209, 209, 209));
        tabFuncionario.setColorFilasBackgound2(new java.awt.Color(250, 250, 250));
        tabFuncionario.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        tabFuncionario.setColorFilasForeground2(new java.awt.Color(102, 102, 102));
        tabFuncionario.setColorForegroundHead(new java.awt.Color(51, 51, 51));
        tabFuncionario.setColorSelBackgound(new java.awt.Color(40, 53, 147));
        tabFuncionario.setFuenteFilas(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tabFuncionario.setFuenteFilasSelect(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tabFuncionario.setFuenteHead(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tabFuncionario.setGridColor(new java.awt.Color(204, 204, 204));
        tabFuncionario.setGrosorBordeFilas(0);
        tabFuncionario.setGrosorBordeHead(0);
        tabFuncionario.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabFuncionario.setMultipleSeleccion(false);
        tabFuncionario.setOpaque(false);
        tabFuncionario.setRowHeight(30);
        tabFuncionario.setSelectionBackground(new java.awt.Color(63, 81, 181));
        tabFuncionario.setShowVerticalLines(false);
        tabFuncionario.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listCliente, tabFuncionario);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${clienteNome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${clienteCPF}"));
        columnBinding.setColumnName("CPF");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${clienteTelefoneCelular}"));
        columnBinding.setColumnName("Celular");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tabFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabFuncionario);
        if (tabFuncionario.getColumnModel().getColumnCount() > 0) {
            tabFuncionario.getColumnModel().getColumn(0).setResizable(false);
            tabFuncionario.getColumnModel().getColumn(1).setResizable(false);
            tabFuncionario.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        kGradientPanel3.setkEndColor(new java.awt.Color(40, 53, 147));
        kGradientPanel3.setkStartColor(new java.awt.Color(26, 35, 126));

        botVoltar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/voltar18px.png"))); // NOI18N
        botVoltar.setText("VOLTAR");
        botVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVoltarActionPerformed(evt);
            }
        });

        botNovo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/add18px.png"))); // NOI18N
        botNovo.setText("INSERIR NOVO CLIENTE");
        botNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(botVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botNovo)
                .addGap(5, 5, 5))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botVoltar)
                    .addComponent(botNovo))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1058, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botFecharActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_botFecharActionPerformed

    private void botAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAlterarActionPerformed

        int linha = -1;
        linha = tabFuncionario.getSelectedRow();
        if (linha != -1) {
            boolean consulta = false;
            cliente = listCliente.get(linha);
            viewDadosCliente alterar = new viewDadosCliente(null, true, cliente, consulta);
            alterar.setVisible(true);
            listCliente.clear();
            listCliente.addAll(contCliente.listarTodos());
            limparLab();
            cliente = null;
        } else {
            JOptionPane.showMessageDialog(null, "SELECIONE ALGUÉM NA TABELA PARA ALTERAR");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_botAlterarActionPerformed

    private void botExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botExcluirActionPerformed

        int linhaExcluir = -1;
        linhaExcluir = tabFuncionario.getSelectedRow();
        if (linhaExcluir != -1) {
            cliente = listCliente.get(linhaExcluir);
            int op = JOptionPane.showConfirmDialog(this,
                    "Confirma a exclusão do Cliente "
                    + cliente.getClienteNome() + "?",
                    "Exclusão de Cliente",
                    JOptionPane.YES_NO_OPTION);

            if (op == JOptionPane.YES_OPTION) {
                try {
                    contCliente.excluir(cliente.getClienteId());
                    listCliente.clear();
                    listCliente.addAll(contCliente.listarTodos());
                    limparLab();
                } catch (NaoExisteException | IntegridadeException e){
                    
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Cliente Na Tabela Para Ser Excluido");
        }

    }//GEN-LAST:event_botExcluirActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased

        if (boxPesquisa.getSelectedItem().equals("NOME")) {
            listCliente.clear();
            listCliente.addAll(contCliente.listarPorNome(txtBuscar.getText()));
        } else {
            listCliente.clear();
            listCliente.addAll(contCliente.listarPorCPF(txtBuscar.getText()));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void botLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimparActionPerformed

        txtBuscar.setText("");
        limparLab();
        listCliente.clear();
        listCliente.addAll(contCliente.listarTodos());

        // TODO add your handling code here:
    }//GEN-LAST:event_botLimparActionPerformed

    private void tabFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabFuncionarioMouseClicked
        int linha = -1;
        linha = tabFuncionario.getSelectedRow();

        if (evt.getClickCount() > 1) {
            boolean consulta = true;
            viewDadosCliente insAlte = new viewDadosCliente(null, true, cliente, consulta);
            insAlte.setVisible(true);
            limparLab();
            listCliente.clear();
            listCliente.addAll(contCliente.listarTodos());
        } else {
            if (linha != -1) {
                cliente = new Cliente();
                cliente = listCliente.get(linha);
                labelNome.setText(cliente.getClienteNome());

                labCidades.setText(cliente.getClienteCidade() + ", Estado: " + cliente.getClienteEstado());
                //   labCidades.setText(Cliente.getClienteRua()+", Estado: "+ Cliente.getClienteEstado());
                laBNomeRua.setText(cliente.getClienteRua() + ", Nº " + String.valueOf(cliente.getClienteRuaNumero()));

                //   laBNomeRua.setText(Cliente.getClienteCidade()+", Nº "+ String.valueOf(Cliente.getClienteRuaNumero()));
                labRG.setText(cliente.getClienteRG());
                labBairro.setText(cliente.getClienteBairro());
                labCPF.setText(cliente.getClienteCPF());
                labDataNasc.setText(formatar.format(cliente.getClienteDataNascimento()));
                labEmail.setText(cliente.getClienteEmail());
//                labEstado.setText(Cliente.getClienteEstado());
//                labNumRua.setText(String.valueOf(Cliente.getClienteRuaNumero()));
                labTelefone.setText(cliente.getClienteTelefoneCelular());
                //  JOptionPane.showMessageDialog(null, Cliente);
            }
        }
    }//GEN-LAST:event_tabFuncionarioMouseClicked

    private void botVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVoltarActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_botVoltarActionPerformed

    private void botNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botNovoActionPerformed

        cliente = null;
        boolean consulta = false;
        // JOptionPane.showMessageDialog(null, funcionario);
        viewDadosCliente dadosFun = new viewDadosCliente(null, true, cliente, consulta);
        dadosFun.setVisible(true);
        listCliente.clear();
        listCliente.addAll(contCliente.listarTodos());
        limparLab();

        // TODO add your handling code here:
    }//GEN-LAST:event_botNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                viewCliente dialog = new viewCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAlterar;
    private javax.swing.JButton botExcluir;
    private javax.swing.JButton botFechar;
    private javax.swing.JButton botLimpar;
    private javax.swing.JButton botNovo;
    private javax.swing.JButton botVoltar;
    private javax.swing.JComboBox<String> boxPesquisa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel laBNomeRua;
    private javax.swing.JLabel labBairro;
    private javax.swing.JLabel labCPF;
    private javax.swing.JLabel labCidades;
    private javax.swing.JLabel labDataNasc;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labRG;
    private javax.swing.JLabel labTelefone;
    private javax.swing.JLabel labelNome;
    private java.util.List<modelo.Cliente> listCliente;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente2;
    private rojerusan.RSPanelImage rSPanelImage1;
    private rojerusan.RSTableMetro tabFuncionario;
    private javax.swing.JTextField txtBuscar;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void limparLab() {
        laBNomeRua.setText("");
        labBairro.setText("");
        labCPF.setText("");
        labRG.setText("");
        labDataNasc.setText(" ");
        labEmail.setText("");
//        labEstado.setText("____");
//        labNumRua.setText("__________");
        labCidades.setText("");
        labTelefone.setText("");
        labelNome.setText("");
    }

}
