/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Fundamental.ComprarProduto;

import controle.ControleCompraProduto;
import controle.ControleFornecedor;
import java.awt.Color;
import java.awt.Font;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.CompraProduto;
import modelo.Fornecedor;

/**
 *
 * @author Maycon
 */
public class CompraProd extends javax.swing.JDialog {

    /**
     * Creates new form CompraProd
     */
    private ControleCompraProduto contConProd = new ControleCompraProduto();
    DefaultTableModel modelo;
    private ArrayList<CompraProduto> listCompraProduto = new ArrayList<>();
    private SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/yyyy");

    DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
    DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();

    public CompraProd(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelo = (DefaultTableModel) tabCompraEfetuada.getModel();
        txtFornecedor.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        atualizarTabela();
        darTamanhoAColuna();

        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        
        tabCompraEfetuada.setFont(new Font("SansSerif", 0, 14));

        direita.setBackground(new java.awt.Color(209, 209, 209));
        direita.setForeground(new java.awt.Color(102, 102, 102));
        esquerda.setBackground(new java.awt.Color(209, 209, 209));
        esquerda.setForeground(new java.awt.Color(102, 102, 102));
        // Border emptyBorder = null;

        // direita.setBorder(emptyBorder);
        tabCompraEfetuada.getColumnModel().getColumn(1).setCellRenderer(direita);
        tabCompraEfetuada.getColumnModel().getColumn(0).setCellRenderer(esquerda);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        botFecharNormal2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabCompraEfetuada = new rojerusan.RSTableMetro();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        botLimpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        botComprar = new javax.swing.JButton();
        botSalvar = new javax.swing.JButton();
        botVisualizar = new javax.swing.JButton();
        dataInicio = new com.toedter.calendar.JDateChooser();
        dataFim = new com.toedter.calendar.JDateChooser();
        botBuscarPorPeriodoEFornecedor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        rSPanelGradiente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botFecharNormal2.setBackground(new java.awt.Color(255, 0, 0));
        botFecharNormal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/fechar34px.png"))); // NOI18N
        botFecharNormal2.setContentAreaFilled(false);
        botFecharNormal2.setFocusable(false);
        botFecharNormal2.setOpaque(true);
        botFecharNormal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botFecharNormal2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COMPRAR PRODUTOS");

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botFecharNormal2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addComponent(botFecharNormal2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabCompraEfetuada.setAutoCreateRowSorter(true);
        tabCompraEfetuada.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tabCompraEfetuada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "EMPRESA", "VALOR", "DATA COMPRA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabCompraEfetuada.setAltoHead(40);
        tabCompraEfetuada.setAutoscrolls(false);
        tabCompraEfetuada.setColorBackgoundHead(new java.awt.Color(250, 250, 250));
        tabCompraEfetuada.setColorFilasBackgound1(new java.awt.Color(209, 209, 209));
        tabCompraEfetuada.setColorFilasBackgound2(new java.awt.Color(209, 209, 209));
        tabCompraEfetuada.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        tabCompraEfetuada.setColorFilasForeground2(new java.awt.Color(102, 102, 102));
        tabCompraEfetuada.setColorForegroundHead(new java.awt.Color(51, 51, 51));
        tabCompraEfetuada.setColorSelBackgound(new java.awt.Color(40, 53, 147));
        tabCompraEfetuada.setFuenteFilas(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tabCompraEfetuada.setFuenteFilasSelect(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tabCompraEfetuada.setFuenteHead(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tabCompraEfetuada.setGridColor(new java.awt.Color(204, 204, 204));
        tabCompraEfetuada.setGrosorBordeFilas(0);
        tabCompraEfetuada.setGrosorBordeHead(0);
        tabCompraEfetuada.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabCompraEfetuada.setMultipleSeleccion(false);
        tabCompraEfetuada.setName(""); // NOI18N
        tabCompraEfetuada.setRowHeight(30);
        tabCompraEfetuada.setSelectionBackground(new java.awt.Color(40, 53, 147));
        tabCompraEfetuada.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabCompraEfetuada);
        if (tabCompraEfetuada.getColumnModel().getColumnCount() > 0) {
            tabCompraEfetuada.getColumnModel().getColumn(0).setResizable(false);
            tabCompraEfetuada.getColumnModel().getColumn(1).setResizable(false);
            tabCompraEfetuada.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("COMPRAS EFETUADAS");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("FORNECEDOR:");

        txtFornecedor.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtFornecedor.setBorder(null);
        txtFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFornecedorKeyReleased(evt);
            }
        });

        botLimpar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        botLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/limpar18px.png"))); // NOI18N
        botLimpar.setText("LIMPAR");
        botLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimparActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel1.setkEndColor(new java.awt.Color(40, 53, 147));
        kGradientPanel1.setkStartColor(new java.awt.Color(26, 35, 126));

        botComprar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        botComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/comprar18px.png"))); // NOI18N
        botComprar.setText("COMPRAR PRODUTO");
        botComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botComprarActionPerformed(evt);
            }
        });

        botSalvar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        botSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/cancel18px.png"))); // NOI18N
        botSalvar.setText("SAIR");
        botSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSalvarActionPerformed(evt);
            }
        });

        botVisualizar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        botVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/verificar18px.png"))); // NOI18N
        botVisualizar.setText("VISUALIZAR COMPRA");
        botVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(botSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(botVisualizar)
                .addGap(1, 1, 1)
                .addComponent(botComprar, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botComprar)
                    .addComponent(botSalvar)
                    .addComponent(botVisualizar))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        dataInicio.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        dataFim.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        botBuscarPorPeriodoEFornecedor.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        botBuscarPorPeriodoEFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons/buscar18px.png"))); // NOI18N
        botBuscarPorPeriodoEFornecedor.setText("BUSCAR");
        botBuscarPorPeriodoEFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBuscarPorPeriodoEFornecedorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("DATA FIM:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("DATA INICIO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botBuscarPorPeriodoEFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botLimpar)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botBuscarPorPeriodoEFornecedor)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botFecharNormal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botFecharNormal2ActionPerformed

        dispose();

    }//GEN-LAST:event_botFecharNormal2ActionPerformed

    private void botSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSalvarActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_botSalvarActionPerformed

    private void botComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botComprarActionPerformed

        EfetuarCompra efeCon = new EfetuarCompra(null, true, null);
        efeCon.setVisible(true);

        atualizarTabela();
        // TODO add your handling code here:
    }//GEN-LAST:event_botComprarActionPerformed

    private void botVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVisualizarActionPerformed
        int linha = -1;
        linha = tabCompraEfetuada.getSelectedRow();
        if (linha != -1) {
            CompraProduto p = listCompraProduto.get(linha);
            EfetuarCompra efeCon = new EfetuarCompra(null, true, p);
            efeCon.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "SELECIONE UMA COMPRA PARA VISUALIZAR O QUE FOI COMPRADO!!!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_botVisualizarActionPerformed

    private void txtFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFornecedorKeyReleased
        listCompraProduto.clear();
        listCompraProduto.addAll(contConProd.listarCompraFornecedor(txtFornecedor.getText()));
        tabelaListaFornecedor(listCompraProduto);
    }//GEN-LAST:event_txtFornecedorKeyReleased

    private void botBuscarPorPeriodoEFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBuscarPorPeriodoEFornecedorActionPerformed

        listCompraProduto.clear();
        if (!(dataInicio.getDate() == null) && !(dataFim.getDate() == null)) {
            if (dataInicio.getDate().before(dataFim.getDate())) {
                listCompraProduto.addAll(contConProd.listarPorPeriodoFornecedor(dataInicio.getDate(), dataFim.getDate()));
                if (listCompraProduto.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "NEM UMA COMPRA NESTE PERÍODO FOI ENCONTRADA!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "DATA INÍCIO NÃO PODE SER MAIOR QUE DATA FIM!");
            }
            tabelaListaFornecedor(listCompraProduto);

        } else {
            JOptionPane.showMessageDialog(null, "SELECIONE UMA DATA INICIO E UMA DATA FIM PARA PESQUISAR!");
        }
    }//GEN-LAST:event_botBuscarPorPeriodoEFornecedorActionPerformed

    private void botLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimparActionPerformed

        JOptionPane.showMessageDialog(null, dataFim.getDate());
        dataFim.setDate(null);
        dataInicio.setDate(null);
        txtFornecedor.setText("");
        JOptionPane.showMessageDialog(null, dataInicio.getDate());
        atualizarTabela();

        // TODO add your handling code here:
    }//GEN-LAST:event_botLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CompraProd dialog = new CompraProd(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botBuscarPorPeriodoEFornecedor;
    private javax.swing.JButton botComprar;
    private javax.swing.JButton botFecharNormal2;
    private javax.swing.JButton botLimpar;
    private javax.swing.JButton botSalvar;
    private javax.swing.JButton botVisualizar;
    private com.toedter.calendar.JDateChooser dataFim;
    private com.toedter.calendar.JDateChooser dataInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private rojerusan.RSTableMetro tabCompraEfetuada;
    private javax.swing.JTextField txtFornecedor;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabela() {

        listCompraProduto.clear();
        ControleFornecedor contFor = new ControleFornecedor();
        listCompraProduto.addAll(contConProd.listarTodos());

        tabelaListaFornecedor(listCompraProduto);

    }

    private void atualizaTabela(ArrayList<CompraProduto> listItem) {

        modelo.setNumRows(0);

        for (CompraProduto i : listItem) {
            double x = i.getValorTotal();
            String v = doubleString(x);
            modelo.addRow(new Object[]{i.getFornecedorCod().getFornecedorRazaoSicial(), doubleString(i.getValorTotal()), i.getDataCompra()});
        }
    }

    public String doubleString(double d) {

        Locale.setDefault(new Locale("pt", "BR"));
        DecimalFormat df = new DecimalFormat("#,##0.00", new DecimalFormatSymbols(new Locale("pt", "BR")));
        String s = df.format(d);
        return s;
    }

    private void darTamanhoAColuna() {
        tabCompraEfetuada.getColumnModel().getColumn(0).setPreferredWidth(200);
        tabCompraEfetuada.getColumnModel().getColumn(1).setPreferredWidth(50);
        tabCompraEfetuada.getColumnModel().getColumn(2).setPreferredWidth(50);
    }

    private void tabelaListaFornecedor(ArrayList<CompraProduto> listaCompraProduto) {

        while (modelo.getRowCount() > 0) {
            // apaga a primeira linha
            modelo.removeRow(0);
        }
        for (CompraProduto p : listCompraProduto) {
            // adiciona uma linha na tabela
            // o object criado tem que ter a mesma quantidade
            // de elementos que foi definida na tabela, 
            // como também os mesmos tipos
            modelo.addRow(new Object[]{p.getFornecedorCod().getFornecedorRazaoSicial(), doubleString(p.getValorTotal()), formatar.format(p.getDataCompra())});
        }
    }
}
